name: butt # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.1.40' # just for humans, typically '1.2+git' or '1.3.2'
summary: butt (broadcast using this tool) is an easy to use streaming tool.
description: |
   butt (broadcast using this tool) is an easy to use, multi OS streaming tool.
   It supports ShoutCast and IceCast and runs on Linux, MacOS and Windows.
   The main purpose of butt is to stream live audio data from your computers Mic or Line input
   to an Shoutcast or Icecast server. Recording is also possible.
   It is NOT intended to be a server by itself or automatically stream a set of audio files.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
architectures:
  - build-on: amd64
    build-for: amd64
  - build-on: arm64
    build-for: arm64
  - build-on: armhf
    build-for: armhf

layout:
  /usr/share/alsa:
     bind: $SNAP/usr/share/alsa
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib

apps:
  butt:
    command: usr/local/bin/butt
    command-chain: ["snap/command-chain/alsa-launch"]
    plugs:
       - home
       - x11
       - desktop
       - network
       - network-bind
       - audio-playback
       - audio-record
       - alsa
       - shared-memory

    extensions: [ gnome ]
    environment:
       DISABLE_WAYLAND: '1'
       ALWAYS_USE_PULSEAUDIO: '1'

plugs:
  shared-memory:
    private: true

parts:
  alsa-mixin:
     plugin: dump
     source: https://github.com/diddlesnaps/snapcraft-alsa.git
     source-subdir: snapcraft-assets
     build-packages:
       - libasound2-dev
     stage-packages:
       - libasound2
       - libasound2-plugins
       - yad
     stage:
       - etc/asound.conf
       - snap/command-chain/alsa-launch
       - usr/bin/yad*
       - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
       - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libasound*
       - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libdnsfile*
       - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libFLAC*
       - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libjack*
       - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libpulse*
       - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libsamplerate*
       - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libspeex*
       - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvorbis*
       - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio

  main:
   source: https://danielnoethen.de/butt/release/0.1.40/butt-0.1.40.tar.gz
   plugin: autotools
   after: [alsa-mixin]
   build-packages:
    - libfltk1.3-dev
    - portaudio19-dev
    - libopus-dev
    - libmp3lame-dev
    - libvorbis-dev
    - libogg-dev
    - libflac-dev
    - libfdk-aac-dev
    - libdbus-1-dev
    - libsamplerate0-dev
    - libssl-dev
    - libcurl4-openssl-dev
   stage-packages:
    - alsa-topology-conf
    - alsa-ucm-conf
    - fontconfig-config
    - fonts-dejavu-core
    - libasound2
    - libasound2-data
    - libflac8
    - libfltk-images1.3
    - libfltk1.3
    - libfontconfig1
    - libjpeg-turbo8
    - libjpeg8
    - libmp3lame0
    - libogg0
    - libopus0
    - libportaudio2
    - libsamplerate0
    - libvorbis0a
    - libvorbisenc2
    - libxcursor1
    - libxfixes3
    - libxft2
    - libxinerama1
    - libxrender1
    - desktop-file-utils
    - libfdk-aac2

lint:
   ignore:
     - library:
       - usr/lib/*/libpulse*
       - usr/lib/*/libjack*
       - usr/lib/*/libfdk-aac*
