name: butt # you probably want to 'snapcraft register <name>'
base: core24 # the base snap is the execution environment for this snap
version: '0.1.46' # just for humans, typically '1.2+git' or '1.3.2'
summary: butt (broadcast using this tool) is an easy to use streaming tool.
description: |
   butt (broadcast using this tool) is an easy to use, multi OS streaming tool.
   It supports ShoutCast and IceCast and runs on Linux, MacOS and Windows.
   The main purpose of butt is to stream live audio data from your computers Mic or Line input
   to an Shoutcast or Icecast server. Recording is also possible.
   It is NOT intended to be a server by itself or automatically stream a set of audio files.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

platforms:
  amd64:
    build-on: amd64
    build-for: amd64
  arm64:
    build-on: arm64
    build-for: arm64

layout:
  /usr/share/alsa:
     bind: $SNAP/usr/share/alsa
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_ON/alsa-lib:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_ON/alsa-lib
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_ON/oss4-libsalsa:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_ON/oss4-libsalsa

apps:
  butt:
    command: usr/local/bin/butt
    command-chain: ["./check.sh"]
    plugs:
       - home
       - x11
       - desktop
       - network
       - network-bind
       - audio-playback
       - audio-record
       - alsa
       - shared-memory

    extensions: [ gnome ]
    environment:
       DISABLE_WAYLAND: '1'

plugs:
  shared-memory:
    private: true

parts:

  main:
   source: https://danielnoethen.de/butt/release/1.45.0/butt-1.45.0.tar.gz
   override-build: |
        craftctl default
        cp -f $CRAFT_PROJECT_DIR/local/check.sh $SNAPCRAFT_PART_INSTALL/
        chmod a+rx $SNAPCRAFT_PART_INSTALL/*.sh
   plugin: autotools
   build-packages:
    - libfltk1.3-dev
    - portaudio19-dev
    - libopus-dev
    - libmp3lame-dev
    - libvorbis-dev
    - libogg-dev
    - libflac-dev
    - libfdk-aac-dev
    - libdbus-1-dev
    - libsamplerate0-dev
    - libssl-dev
    - libportmidi-dev
    - libcurl4-openssl-dev
   stage-packages:
    - alsa-topology-conf
    - alsa-ucm-conf
    - fontconfig-config
    - fonts-dejavu-core
    - libasound2
    - libasound2-data
    - libflac12t64
    - libfltk-images1.3
    - libfltk1.3
    - libfontconfig1
    - libjpeg-turbo8
    - libjpeg8
    - libmp3lame0
    - libogg0
    - libopus0
    - libportaudio2
    - libsamplerate0
    - libvorbis0a
    - libvorbisenc2
    - libxcursor1
    - libxfixes3
    - libxft2
    - libxinerama1
    - libxrender1
    - desktop-file-utils
    - libfdk-aac2
    - libportmidi0
    - libavcodec60
    - libproxy1v5
    - liboss4-salsa2
    - zenity

lint:
   ignore:
     - library
